name: Delete backport branch

on:
  pull_request:
    types: [closed]

jobs:
  delete:
    if: startsWith(github.head_ref, 'backport/')
    runs-on: ubuntu-latest
    steps:
      - name: Delete backport branch
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${context.payload.pull_request.head.ref}`,
            })
